### ISSUE TITLE
关于快速开始中 Vue.use()的使用

### ISSUE THREAD

**Issue by askwuxue** [varletjs/varlet-vue2#43]
# Bug report 🐞
CDN
<div id="app"></div>
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script>
<script src="https://cdn.jsdelivr.net/npm/@varlet-vue2/ui/umd/varlet.js"></script>
<script>
  const App = Vue.use({
    template: '<var-button>按钮</var-button>'
  })
  new Vue({
     render: h => h(App)
  }).$mount('#app')
</script>

您好，我使用了快速开始中CDN导入的代码，没有正确结果产生，Vue.use()接受一个对象且具有install()方法，上述的代码，求解。

## Version & Environment
Chrome

**Comment by haoziqaq** [comment]
这应该是一个typo的错误，我来修复一下吧

**Comment by askwuxue** [comment]
如果可以的话，我也可以帮忙，只是刚开始接触，还不太清楚。如果您可以帮忙提供思路，不胜感激。

**Comment by haoziqaq** [comment]
修复了 迁移只花了一个月 可能是不够仔细 在发布正式版之前我们会仔细修订一次文档  欢迎协助我们整理一下文档

**Comment by haoziqaq** [comment]
确实太不仔细了 我负责批评他！

**Comment by askwuxue** [comment]
好的，谢谢

**Comment by haoziqaq** [comment]
如果可以的话 可以帮忙优化和修订一下文档 因为组织成员目前都focus在单元测试上 文档方面应该是存在很多问题

**Comment by askwuxue** [comment]
嗯，好的，发现问题的话，我会尽力帮助修复的。我刚才也在看单元测试，我刚才跑了一下单元测试，发现还有蛮多case没写的，本来想研究一下，看能不能帮忙写一下单元case。然后碰巧发现了文档的小问题。

**Comment by haoziqaq** [comment]
嗯 好的 感谢
