### ISSUE TITLE
时间选择器

### ISSUE THREAD

**Issue by cuitengf** [varletjs/varlet-vue2#47]
# About `styles` 🛠️
datepicker 和 timepicker  这两个时间选择器交互给个👍( 第一次看到移动端在时间picker 上加head, 交互很清晰. )
timepicker 期待优化选择, 当我在圆盘选择时间的时候, 没有什么感知. 很懵, 当我看到已经切换时分秒的时候才知道组件的意思. 

(后续会不会有小程序端, 和react版本?)

**Comment by cuitengf** [comment]
后续会不会有小程序端, 和react版本?

**Comment by bilibili-ayang** [comment]
timepicker组件的优化我们会考虑如何优化，或者说您有好想法的话也欢迎给我们投稿！👏

至于会不会出其它框架的版本，我们的态度是，鼓励开发，看看谁愿意带头去做，我们会提供第一方支持！
