### ISSUE TITLE
var-pull-refresh 与 var-list混合使用滚动条在任意位置下拉都会触发刷新

### ISSUE THREAD

**Issue by linnxx** [varletjs/varlet-vue2#48]
# Bug report 🐞
var-pull-refresh 与 var-list混合使用滚动条在任意位置下拉都会触发刷新。我看了源码，必须是pull-refresh的外部scroller的scrollTop==0时才会触发刷新，获取scroller的条件就是上级节点的overflow为auto或者 scroll。这两个条件我看都满足，我也测试打印了 `page-list`节点的scrollTop值是不为0。

感谢各位指导下~

css:
```
.page-list {
    height: calc(100% - 40px);
    overflow: auto;
}
```
html:
```
<div class="page-list" >
        <var-pull-refresh ref="puller" v-model="isRefresh" @refresh="refresh">
            <var-list :finished="finished" @load="load"></var-list>
       </var-pull-refresh>
</div>
```

## Version & Environment
微信浏览器

## Expectation
当回到顶部时才触发下拉刷新

## Actual results (or Errors)
在列表底部，向下滑动距离较大时（下拉刷新的触发距离）就触发了刷新

**Comment by BeADre** [comment]
很抱歉这么久才回复 接下来我会去调查一下

**Comment by BeADre** [comment]
https://user-images.githubusercontent.com/34639100/163799357-1e879d12-46c5-46f8-8143-fa86e6f0e9ad.mp4


我不能复现你的问题

**Comment by linnxx** [comment]
我周末再验证下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月18日(周一) 晚上7:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet-vue2] var-pull-refresh 与 var-list混合使用滚动条在任意位置下拉都会触发刷新 (Issue #48)




 
https://user-images.githubusercontent.com/34639100/163799357-1e879d12-46c5-46f8-8143-fa86e6f0e9ad.mp4
 
我不能复现你的问题
