### ISSUE TITLE
select组件报错

### ISSUE THREAD

**Issue by peshje8023** [varletjs/varlet-vue2#59]
# Bug report 🐞
直接使用基础示例，
`<var-select placeholder="请选择一个选项" v-model="value">
  <var-option label="吃饭" />
</var-select>`
无法打开下拉菜单，控制台报错如下：
TypeError: Cannot read properties of null (reading 'wrapWidth')
![image](https://user-images.githubusercontent.com/22843049/191398622-564842d2-2acb-47b0-9ffd-93f61085f3e7.png)

## Version & Environment
"@varlet-vue2/ui": "^0.1.2"
"vue": "^2.6.14"

**Comment by haoziqaq** [comment]
可以提供一个复现问题的仓库么？

**Comment by peshje8023** [comment]
https://gitee.com/peshje/varlet-demo

**Comment by haoziqaq** [comment]
请把版本锁定在vue2.6.14，我们没有去对 vue2.7 进行适配。 错误原因是因为 vue2.7 的升级引起的不兼容。

**Comment by haoziqaq** [comment]
并且把组件库升级到最新版
