### ISSUE TITLE
Select选择框Bug

### ISSUE THREAD

**Issue by bynowi** [varletjs/varlet-vue2#60]
# Bug report 🐞

Option无法渲染

## Version & Environment

"@varlet-vue2/ui": "^0.1.4",
"vue": "^2.6.14",
node: v16.18.0

使用了 postcss-px-to-viewport 移动端适配方案

## Expectation

option无法渲染

![截图](https://user-images.githubusercontent.com/20673319/198256912-17b6be5a-91ad-4601-b6fe-f1ebe091e936.png)

**Comment by haoziqaq** [comment]
我们没有对 vue2.7 版本做兼容，请锁定 vue 的版本在 2.6。强烈推荐直接使用 vue3进行开发



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月27日(周四) 晚上6:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [varletjs/varlet-vue2] Select选择框Bug (Issue #60)




 
Bug report 🐞
 
Option无法渲染
 
Version &amp; Environment
 
***@***.***/ui": "^0.1.4",
 "vue": "^2.6.14",
 node: v16.18.0
 
使用了 postcss-px-to-viewport 移动端适配方案
 
Expectation
 
option无法渲染

**Comment by bynowi** [comment]
感谢，看了历史issues，知道什么情况了

**Comment by haoziqaq** [comment]
不客气不客气



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月27日(周四) 晚上6:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet-vue2] Select选择框Bug (Issue #60)




 
感谢，看了历史issues，知道什么情况了
