### ISSUE TITLE
Form组件

### ISSUE THREAD

**Issue by bynowi** [varletjs/varlet-vue2#61]
# Bug report 🐞
表单校验返回值一直是 false
使用下方这种方式调用，请问能给个接口调用demo吗
![image](https://user-images.githubusercontent.com/20673319/199152577-1b10d6ef-78e9-41a3-b42d-f0e176577ef1.png)

**Comment by haoziqaq** [comment]
方便提供一个最小化的复现 demo 么？

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月1日(周二) 中午11:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [varletjs/varlet-vue2] Form组件 (Issue #61)




 
Bug report 🐞
 
表单校验返回值一直是 false
 使用下方这种方式调用，请问能给个接口调用demo吗
 
 
Version &amp; Environment
 
Expectation
 
Actual results (or Errors)

**Comment by bynowi** [comment]
这个仓库你看下，谢谢 ，头一次用这个框架不熟悉怎么使用，错误之处还请指出 ，谢谢 https://github.com/bynowi/varlet_vue2_demo.git

**Comment by haoziqaq** [comment]
确定是 bug, 升级到 0.1.5 解决问题。 另外 vue2 版本目前处于无新特性更新的维护状态，如果条件允许，强烈推荐使用 varlet vue3 版本进行开发。

**Comment by bynowi** [comment]
考虑到老旧设备问题，目前还没办法升级到vue2，太难了 T _ T ， 大佬，0.1.5什么时候发布
