### ISSUE TITLE
Space 间隔 靠右属性 无效

### ISSUE THREAD

**Issue by jjjjjmmmmm** [varletjs/varlet-vue2#62]
# Bug report 🐞
pc浏览器模拟h5有效，但微信内无效。
<img width="355" alt="image" src="https://user-images.githubusercontent.com/11729775/201258793-d472a043-cae1-466b-9e71-99310bbbf87e.png">
建议参数justify 增加可选值 flex-end
## Version & Environment
0.1.5
微信开发者工具、微信pc客户端、部分安卓浏览器

**Comment by qytayh** [comment]
感谢反馈，已修复该问题，将在下个小版本中体现

**Comment by jjjjjmmmmm** [comment]
谢谢
