### ISSUE TITLE
Dialog, Snackbar组件函数调用调用时，options选项title,content无效，页面不显示。

### ISSUE THREAD

**Issue by ll60** [varletjs/varlet-vue2#63]
# Bug report 🐞

## Version & Environment
@varlet-vue2/ui: 0.1.6
vue: 2.6.12

## Expectation
页面弹窗里面文字标题和内容能正常显示

## Actual results (or Errors)
弹窗正常弹出，但是里面没有标题和内容。

**Comment by ll60** [comment]
吐槽一下，好家伙，看到v3尤大推荐过这个v3版的，v2版的都没经过测试吗，本来还想用一下，刚开始用就各种致命bug, dialog的border-radius也无效，var-diaog容器被var-popup__content给挡住了样式。

**Comment by haoziqaq** [comment]
![image](https://user-images.githubusercontent.com/24223652/203027159-3da56c5d-34d4-45e9-b070-7c776f79dcca.png)
没复现你的问题

**Comment by ll60** [comment]
<img width="843" alt="image" src="https://user-images.githubusercontent.com/30487969/203027503-425627c3-09d2-4435-a47f-ae87b9893d46.png">
![image](https://user-images.githubusercontent.com/30487969/203027573-d990c684-58d6-4af7-9136-bc4339b1bfd4.png)

**Comment by ll60** [comment]
> ![image](https://user-images.githubusercontent.com/24223652/203027159-3da56c5d-34d4-45e9-b070-7c776f79dcca.png) 没复现你的问题

<img width="750" alt="image" src="https://user-images.githubusercontent.com/30487969/203027715-02edec12-7c83-45d6-8e4e-921e2e17c745.png">

![image](https://user-images.githubusercontent.com/30487969/203027926-cd5c262f-4736-4185-811c-f78b15505475.png)

**Comment by ll60** [comment]
> ![image](https://user-images.githubusercontent.com/24223652/203027159-3da56c5d-34d4-45e9-b070-7c776f79dcca.png) 没复现你的问题

可以贴下你的代码吗

**Comment by haoziqaq** [comment]
![image](https://user-images.githubusercontent.com/24223652/203028044-c797f61d-d676-44b0-ae7d-5362be9db739.png)
![image](https://user-images.githubusercontent.com/24223652/203028130-e60c7ac7-babc-4eff-845d-3c361ff3d099.png)

**Comment by ll60** [comment]
> ![image](https://user-images.githubusercontent.com/24223652/203028044-c797f61d-d676-44b0-ae7d-5362be9db739.png) ![image](https://user-images.githubusercontent.com/24223652/203028130-e60c7ac7-babc-4eff-845d-3c361ff3d099.png)

....🤔阿这。。。

**Comment by ll60** [comment]
![image](https://user-images.githubusercontent.com/30487969/203029403-7d5a41ef-722d-4a23-a679-c364978e94c0.png)
我这个咋是空的。。。

**Comment by haoziqaq** [comment]
可以提供一个 demo，我来帮你检查一下。顺道一提，现在 vue2 的官方预设基本都是 2.7 的预设，varlet vue2 的版本是社区推动出来的，后被放到了 varletjs 组织里进行维护（主要原因也是最早的推动者不愿意维护了），目前也处于只修复严重 bug 的状态。有条件的话，我推荐应该都去使用 vue3 的版本。

**Comment by ll60** [comment]
> 可以提供一个 demo，我来帮你检查一下。顺道一提，现在 vue2 的官方预设基本都是 2.7 的预设，varlet vue2 的版本是社区推动出来的，后被放到了 varletjs 组织里进行维护（主要原因也是最早的推动者不愿意维护了），目前也处于只修复严重 bug 的状态。有条件的话，我推荐应该都去使用 vue3 的版本。

用的是2.6.x，主要是老项目轮子。新的v3倒是没什么问题，

**Comment by haoziqaq** [comment]
这是我的复现demo的依赖，
![image](https://user-images.githubusercontent.com/24223652/203031565-523a39d2-c3c2-4492-8df7-61ed7f0e109c.png)
用 create-vue 去生成的，用的 vue2.6 的 vite 插件。可以参考一下，还存在问题的话，可以开个 repo，把地址贴在这边，我来进一步定位问题。

**Comment by ll60** [comment]
> 这是我的复现demo的依赖，
> ![image](https://user-images.githubusercontent.com/24223652/203031565-523a39d2-c3c2-4492-8df7-61ed7f0e109c.png)
> 用 create-vue 去生成的，用的 vue2.6 的 vite 插件。可以参考一下，还存在问题的话，可以开个 repo，把地址贴在这边，我来进一步定位问题。

233，刚用新脚手架确实没问题，老项目不行。明白了🫡，v3再考虑用，v2老项目暂时不宜用

**Comment by ll60** [comment]
> 这是我的复现demo的依赖， ![image](https://user-images.githubusercontent.com/24223652/203031565-523a39d2-c3c2-4492-8df7-61ed7f0e109c.png) 用 create-vue 去生成的，用的 vue2.6 的 vite 插件。可以参考一下，还存在问题的话，可以开个 repo，把地址贴在这边，我来进一步定位问题。

真相了，用vue 2.6.12版本或者以下版本，会出现这种情况。升级了vue版本就没问题了。

**Comment by haoziqaq** [comment]
好的～🍉



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月22日(周二) 上午9:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet-vue2] Dialog, Snackbar组件函数调用调用时，options选项title,content无效，页面不显示。 (Issue #63)




  
这是我的复现demo的依赖，  用 create-vue 去生成的，用的 vue2.6 的 vite 插件。可以参考一下，还存在问题的话，可以开个 repo，把地址贴在这边，我来进一步定位问题。
  
真相了，用vue 2.6.12版本或者以下版本，会出现这种情况。升级了vue版本就没问题了。
