### ISSUE TITLE
求一份文档, 能内网部署的

### ISSUE THREAD

**Issue by sun247587578** [varletjs/varlet-vue2#66]
公司内部没网, 而且不能带自己的笔记本, 想问问有没有离线版文档

**Comment by haoziqaq** [comment]
https://github.com/varletjs/varlet-vue2/blob/dev/packages/varlet-vue2-ui/docs/home.zh-CN.md
https://github.com/varletjs/varlet-vue2/blob/dev/packages/varlet-vue2-ui/src/button/docs/zh-CN.md

这两个位置是组件库和组件相关的文档

**Comment by sun247587578** [comment]
https://varlet.gitee.io/varlet-ui-vue2/#/zh-CN/home

**Comment by sun247587578** [comment]
[https://varlet.gitee.io/varlet-ui-vue2/#/zh-CN/home](url)
我想将这个文档部署到内网上

**Comment by haoziqaq** [comment]
你可以 clone 整个仓库

`pnpm bootstrap && cd packages/varlet-vue2-ui && pnpm build`

会产生一个 `packages/varlet-vue2-ui/site`，然后部署它.

**Comment by sun247587578** [comment]
感谢大佬
