### ISSUE TITLE
这个只能在h5上使用吗

### ISSUE THREAD

**Issue by hongjie-zhou** [varletjs/varlet-vue2#67]
# Feature request 🚀

### Expected:

- No breaking changes

### Examples:

```js

```

**Comment by haoziqaq** [comment]
web场景，webview，桌面应用，h5，一切web渲染场景



---原始邮件---
发件人: "hongjie ***@***.***&gt;
发送时间: 2023年1月11日(周三) 下午4:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [varletjs/varlet-vue2] 这个只能在h5上使用吗 (Issue #67)




 
Feature request 🚀
 
Expected:
  
No breaking changes
  
Examples:
 
 
Programme:
 
Others:
