### ISSUE TITLE
扩展组件 , 有没有类似于Element make自动创建扩展组件的命令啊

### ISSUE THREAD

**Issue by sun247587578** [varletjs/varlet-vue2#68]
想依赖varlet为基础UI框架 , 根据公司UI设计再扩展几个插件用 , 有没有类似于Element make自动创建的命令 , 因为自己手动建需要建的文件有点多

**Comment by haoziqaq** [comment]
vue2 版本不会再有新特性加入，只会维护现有功能。 建议转到 varlet vue3 版本。 varlet-cli 可以帮助你进行组件的编写。

**Comment by sun247587578** [comment]
OK. 谢谢 , 公司内网开发环境是Win7 , vue3及其部分插件可能有些问题跑不起来 , 没敢轻易尝试

**Comment by sun247587578** [comment]
嗯嗯 , 非常感谢
