### ISSUE TITLE
select组件，不知道是不是bug，找了很久也没有发现什么错误，感觉很迷糊，v-model没有绑错，option值也没有写错，一加上select就会报错，不知道是不是bug

### ISSUE THREAD

**Issue by zxlovezly** [varletjs/varlet-vue2#72]
# Bug report 🐞

## Version & Environment

![微信图片_20231018172729](https://github.com/varletjs/varlet-vue2/assets/26692206/cee039eb-4d6a-4543-9de0-22415aa21454)
![微信图片_20231018172735](https://github.com/varletjs/varlet-vue2/assets/26692206/db767d84-e4ad-4a0e-87f3-8e4dbc02dbdc)
![微信图片_20231018172739](https://github.com/varletjs/varlet-vue2/assets/26692206/2e225f82-b037-4d0f-943d-1b2a6d5e3b36)
 @haoziqaq

**Comment by haoziqaq** [comment]
是否使用了vue2.7



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月19日(周四) 上午9:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: [varletjs/varlet-vue2] select组件，不知道是不是bug，找了很久也没有发现什么错误，感觉很迷糊，v-model没有绑错，option值也没有写错，一加上select就会报错，不知道是不是bug (Issue #72)




 
Bug report 🐞
 
Version &amp; Environment
 

 
 
 @haoziqaq
 
Expectation
 
Actual results (or Errors)

**Comment by zxlovezly** [comment]
不是vue2.7  vue版本是2.5.2

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年10月19日 9:43
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [varletjs/varlet-vue2] select组件，不知道是不是bug，找了很久也没有发现什么错误，感觉很迷糊，v-model没有绑错，option值也没有写错，一加上select就会报错，不知道是不是bug (Issue #72)

是否使用了vue2.7



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月19日(周四) 上午9:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: [varletjs/varlet-vue2] select组件，不知道是不是bug，找了很久也没有发现什么错误，感觉很迷糊，v-model没有绑错，option值也没有写错，一加上select就会报错，不知道是不是bug (Issue #72)





Bug report 🐞

Version &amp; Environment




@haoziqaq

Expectation

Actual results (or Errors)

**Comment by haoziqaq** [comment]
尝试升级到 vue2.6.14 看看是否能解决问题

**Comment by zxlovezly** [comment]
好的，我试试

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年10月19日 10:33
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [varletjs/varlet-vue2] select组件，不知道是不是bug，找了很久也没有发现什么错误，感觉很迷糊，v-model没有绑错，option值也没有写错，一加上select就会报错，不知道是不是bug (Issue #72)


尝试升级到 vue2.6.14 看看是否能解决问题

―

**Comment by zxlovezly** [comment]
不行，升级到2.6.14还是那个错误

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年10月19日 10:33
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [varletjs/varlet-vue2] select组件，不知道是不是bug，找了很久也没有发现什么错误，感觉很迷糊，v-model没有绑错，option值也没有写错，一加上select就会报错，不知道是不是bug (Issue #72)


尝试升级到 vue2.6.14 看看是否能解决问题

―

**Comment by haoziqaq** [comment]
晚点我尝试复现一下，如果方便的话可以提供一个复现demo



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月19日(周四) 上午10:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet-vue2] select组件，不知道是不是bug，找了很久也没有发现什么错误，感觉很迷糊，v-model没有绑错，option值也没有写错，一加上select就会报错，不知道是不是bug (Issue #72)




 不行，升级到2.6.14还是那个错误 
 
 从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986&gt;发送 
 
 发件人: ***@***.***&gt; 
 发送时间: 2023年10月19日 10:33 
 收件人: ***@***.***&gt; 
 抄送: ***@***.***&gt;; ***@***.***&gt; 
 主题: Re: [varletjs/varlet-vue2] select组件，不知道是不是bug，找了很久也没有发现什么错误，感觉很迷糊，v-model没有绑错，option值也没有写错，一加上select就会报错，不知道是不是bug (Issue #72) 
 
 
 尝试升级到 vue2.6.14 看看是否能解决问题 
 
 ―

**Comment by haoziqaq** [comment]
没能复现这个问题。

```json
{
  "name": "my-vue-app",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview"
  },
  "dependencies": {
    "@varlet-vue2/ui": "^0.1.8",
    "vue": "2.6.14"
  },
  "devDependencies": {
    "vite": "^4.5.0",
    "vite-plugin-vue2": "^2.0.3",
    "vue-template-compiler": "2.6.14"
  }
}

```

**Comment by zxlovezly** [comment]
发了一份demo，代码中的图片没有一并发送，vue已降级到2.5.2

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: haoziqaq ***@***.***>
发送时间: Thursday, October 19, 2023 10:33:09 AM
收件人: varletjs/varlet-vue2 ***@***.***>
抄送: 周雄 ***@***.***>; Author ***@***.***>
主题: Re: [varletjs/varlet-vue2] select组件，不知道是不是bug，找了很久也没有发现什么错误，感觉很迷糊，v-model没有绑错，option值也没有写错，一加上select就会报错，不知道是不是bug (Issue #72)


尝试升级到 vue2.6.14 看看是否能解决问题

―

**Comment by haoziqaq** [comment]
demo 地址在哪里呢？
